tap 'homebrew/cask-drivers'
tap 'epk/epk'

brew 'composer'
brew 'dnsmasq'
brew 'gh'
brew 'mackup'
brew 'mas'
brew 'nginx'
brew 'node'
brew 'php'
brew 'php@7.3'
brew 'php@7.4'
brew 'starship'
brew 'trash'
brew 'tree'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

cask '1password'
cask 'chrome'
cask 'discord'
cask 'docker'
cask 'firefox'
cask 'font-sf-mono-nerd-font'
cask 'github'
cask 'helo'
cask 'iterm2'
cask 'kaleidoscope'
cask 'nordvpn'
cask 'nova'
cask 'slack'
cask 'the-unarchiver'
cask 'tinkerwell'
cask 'visual-studio-code'

mas 'Moom', id: 419330170
